#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t kz"

$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.modversion`";
$L "_|    _|                          _|_|      _|_|  _|            _|            _|";
$L "_|    _|  _|_|_|      _|_|      _|        _|            _|_|_|        _|_|_|  _|";
$L "_|    _|  _|    _|  _|    _|  _|_|_|_|  _|_|_|_|  _|  _|        _|  _|    _|  _|";
$L "_|    _|  _|    _|  _|    _|    _|        _|      _|  _|        _|  _|    _|  _|";
$L "  _|_|    _|    _|    _|_|      _|        _|      _|    _|_|_|  _|    _|_|_|  _|"; 

